version: '3'
services:
  db:
    image: postgres:14.12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: preflight-user
      POSTGRES_PASSWORD: preflight-pass
      POSTGRES_DB: preflight-dev

  web:
    build: .
    entrypoint: ./docker-web-entrypoint.sh
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/preflight
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
