development:
  adapter: postgresql
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  database: <%= ENV.fetch("POSTGRES_DB", "preflight-dev") %>
  username: <%= ENV.fetch("POSTGRES_USER", "") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "") %>
  pool: 10
  timeout: 5000

test:
  adapter: postgresql
  database: preflight-test
  pool: 10
  timeout: 5000
